// <auto-generated />
using System;
using Employee_Leave_Management_System_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_Leave_Management_System_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Employee_Leave_Management_System_backend.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annual")
                        .HasColumnType("int");

                    b.Property<int>("Casual")
                        .HasColumnType("int");

                    b.Property<int>("CompOff")
                        .HasColumnType("int");

                    b.Property<int>("Earned")
                        .HasColumnType("int");

                    b.Property<int>("Sick")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Annual = 12,
                            Casual = 6,
                            CompOff = 4,
                            Earned = 10,
                            Sick = 8,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Annual = 11,
                            Casual = 5,
                            CompOff = 3,
                            Earned = 9,
                            Sick = 7,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            Annual = 10,
                            Casual = 4,
                            CompOff = 2,
                            Earned = 8,
                            Sick = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            Annual = 14,
                            Casual = 7,
                            CompOff = 5,
                            Earned = 12,
                            Sick = 9,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            Annual = 12,
                            Casual = 6,
                            CompOff = 3,
                            Earned = 10,
                            Sick = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 6,
                            Annual = 11,
                            Casual = 5,
                            CompOff = 2,
                            Earned = 9,
                            Sick = 7,
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            Annual = 9,
                            Casual = 4,
                            CompOff = 1,
                            Earned = 8,
                            Sick = 6,
                            UserId = 10
                        },
                        new
                        {
                            Id = 8,
                            Annual = 12,
                            Casual = 6,
                            CompOff = 3,
                            Earned = 10,
                            Sick = 8,
                            UserId = 11
                        },
                        new
                        {
                            Id = 9,
                            Annual = 10,
                            Casual = 5,
                            CompOff = 2,
                            Earned = 9,
                            Sick = 7,
                            UserId = 12
                        });
                });

            modelBuilder.Entity("Employee_Leave_Management_System_backend.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Employee_Leave_Management_System_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "manager1@test.com",
                            Password = "12345",
                            Role = "MANAGER"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager2@test.com",
                            Password = "12345",
                            Role = "MANAGER"
                        },
                        new
                        {
                            Id = 3,
                            Email = "manager3@test.com",
                            Password = "12345",
                            Role = "MANAGER"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emp1@test.com",
                            ManagerId = 1,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 5,
                            Email = "emp2@test.com",
                            ManagerId = 1,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emp3@test.com",
                            ManagerId = 1,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 7,
                            Email = "emp4@test.com",
                            ManagerId = 2,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 8,
                            Email = "emp5@test.com",
                            ManagerId = 2,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 9,
                            Email = "emp6@test.com",
                            ManagerId = 2,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 10,
                            Email = "emp7@test.com",
                            ManagerId = 3,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 11,
                            Email = "emp8@test.com",
                            ManagerId = 3,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 12,
                            Email = "emp9@test.com",
                            ManagerId = 3,
                            Password = "12345",
                            Role = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Employee_Leave_Management_System_backend.Models.LeaveBalance", b =>
                {
                    b.HasOne("Employee_Leave_Management_System_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Employee_Leave_Management_System_backend.Models.LeaveRequest", b =>
                {
                    b.HasOne("Employee_Leave_Management_System_backend.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee_Leave_Management_System_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
